# Generated by Django 3.1.6 on 2021-02-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210210_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'APPROVE'), (2, 'REJECT')], default=2),
        ),
    ]
