# Generated by Django 3.1.6 on 2021-02-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210210_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'APPROVE'), (2, 'REJECT')], default=2, null=True),
        ),
    ]
