# Generated by Django 3.1.6 on 2021-02-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210210_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'APPROVE'), (2, 'REJECT')], null=True),
        ),
    ]
